- name: Commit Backup
  run: |
    git config --global user.name "backup-bot"
    git config --global user.email "backup@github.com"
    git add .
    git commit -m "Auto Firebase Backup" || echo "No changes"
    git push
